baseUrl: https://mareabot.org
languageCode: it-it
theme: terminal
paginate: 5
defaultContentLanguage: it
publishDir: docs

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: post
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: blue
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: true
  # center theme with default width
  centerTheme: true

languages:
  it:
    languageName: Italiano
    title: Marea Bot Telegram
    subtitle: Bot Telegram per la acqua alta a Venezia
    keywords: ""
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Marea Bot
        logoHomeLink: /

      twitter:
        creator: fundor333
        site: https:fundor333.com

    menu:
      main:
        - identifier: about
          name: Sul Bot
          url: /about
        - identifier: telegram
          name: Telegram
          url: https://t.me/mareavenezia
        - identifier: codice
          name: Codice
          url: https://github.com/samarcandaproject/MareaBot
