baseUrl: https://venicebotcenter.org
languageCode: it-it
theme: hello-friend
defaultContentLanguage: it
disqusShortname: venice-bot-center
publishDir: docs
paginate: 5
googleAnalytics: G-GP45MH9DVJ

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: post
  # "dark" or "light"
  defaultTheme: dark
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3

languages:
  it:
    title: Venice Bot Center
    subtitle: Bots Telegram per la acqua alta e pollini a Venezia
    keywords: ""
    menuMore: Show more
    writtenBy: Di
    readMore: Leggi di più
    readOtherPosts: Leggi altro
    newerPosts: Post più recenti
    olderPosts: Post più vecchi
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02

    params:
      logo:
        path: /blue.png
        alt: Marea Bot
    menu:
      main:
        - identifier: about
          name: Sul Bot
          url: /about
        - identifier: telegram
          name: Telegram
          url: https://t.me/mareavenezia
        - identifier: codice
          name: Codice
          url: https://github.com/samarcandaproject/MareaBot
